services:
  - type: web
    name: sahidaam
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: FLASK_ENV
        value: production

      - key: SECRET_KEY
        generateValue: true

      - key: PYTHONUNBUFFERED
        value: "1"

      - key: SESSION_TYPE
        value: filesystem

      - key: DATABASE_URL
        fromDatabase:
          name: sahidaam-db
          property: connectionString

      - key: MAIL_SERVER
        value: smtp.gmail.com

      - key: MAIL_PORT
        value: "587"

      - key: MAIL_USE_TLS
        value: "true"

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: sahidaam-db
    plan: free
